FROM ubuntu:focal

ENV DEBIAN_FRONTEND noninteractive
RUN apt update --yes \
 && apt install --yes \
    build-essential autoconf automake bison flex libtool gawk alien fakeroot \
    dkms libblkid-dev uuid-dev libudev-dev libssl-dev zlib1g-dev libaio-dev \
    libattr1-dev libelf-dev python3 python3-dev python3-setuptools python3-cffi libffi-dev


