FROM debian:buster-slim

ENV DEBIAN_FRONTEND noninteractive
RUN apt update --yes \
 && apt install --yes \
    alien autoconf automake bison build-essential dkms fakeroot flex gawk \
    libaio-dev libattr1-dev libblkid-dev libelf-dev libffi-dev libssl-dev \
    libtool libudev-dev python3 python3-cffi python3-dev python3-setuptools uuid-dev zlib1g-dev


